import 'System'
import 'UnityEngine'
import 'Assembly-CSharp'    -- The user-code assembly generated by Unity.

local Speed = 180;

function Update()

    transform:Rotate(0.0, 0.0, Speed * Time.deltaTime * -1.0, Space.World)

end