name: Unity builds
run-name: ${{ github.actor }} start a build 🚀
on:
  push:
    branches:
      - main
      - features/github-actions # For testing. Should be remove after merge in main
jobs:
  build-windows:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache files
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      - name: Build StandaloneWindows64
        uses: game-ci/unity-builder@v4
        id: buildStep
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneWindows64
          buildName: CGW
          versioning: Semantic

      - uses: actions/upload-artifact@v4
        name: Upload StandaloneWindows64
        id: uploadStep
        with:
          name: CGW-Win-${{ steps.buildStep.outputs.buildVersion }}
          path: |
            build
            !build/**/*_DoNotShip

  build-osx:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache files
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      - name: Build StandaloneOSX
        uses: game-ci/unity-builder@v4
        id: buildStep
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneOSX
          buildName: CGW
          versioning: Semantic

      - name: Archive OSX export 
      - run: tar -cvf build.tar build

      - uses: actions/upload-artifact@v4
        name: Upload StandaloneOSX
        id: uploadStep
        with:
          name: CGW-Osx-${{ steps.buildStep.outputs.buildVersion }}
          path: build.tar