name: Unity builds
run-name: ${{ github.actor }} start a build 🚀

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - fix/macos-export

jobs:

  windows-export:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Cache files
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-
      - name: Build 
        id: build
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneWindows64
          buildName: CGW
          versioning: Semantic
      - name: Upload
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: CGW-StandalonWindows64-${{ steps.build.outputs.buildVersion }}
          path: build/StandaloneWindows64
      - name: Discord notification
        uses: rjstone/discord-webhook-notify@v1
        if: failure()
        with:
          severity: error
          description: '**StandaloneWindows64** build failed'
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

  macos-export:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Cache files
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-
      - name: Build 
        id: build
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneOSX
          buildName: CGW
          versioning: Semantic
      - name: Upload
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: CGW-StandaloneOSX-${{ steps.build.outputs.buildVersion }}
          path: build/StandaloneOSX/CGW.app
      - name: Discord notification
        uses: rjstone/discord-webhook-notify@v1
        if: failure()
        with:
          severity: error
          description: '**StandaloneOSX** build failed'
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

  discord-notification:
    runs-on: ubuntu-latest
    needs: [windows-export, macos-export]
    steps:
      - name: Discord notification
        uses: rjstone/discord-webhook-notify@v1
        if: success()
        with:
          severity: info
          description: '**Version ${{needs.windows-export.build.outputs.buildVersion}}**'
          details: |
            [Windows 64](${{ needs.windows-export.upload.outputs.artifact-url }})
            [MacOS universal](${{ needs.macos-export.upload.outputs.artifact-url }})
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}